/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthorCard: typeof import('./src/components/author/AuthorCard.vue')['default']
    AuthorList: typeof import('./src/components/rank/AuthorList.vue')['default']
    BookCard: typeof import('./src/components/BookCard.vue')['default']
    BookList: typeof import('./src/components/BookList.vue')['default']
    BookRank: typeof import('./src/components/BookRank.vue')['default']
    BookRankList: typeof import('./src/components/rank/BookRankList.vue')['default']
    Bookshelf: typeof import('./src/components/user/Bookshelf.vue')['default']
    CommentCard: typeof import('./src/components/comment/CommentCard.vue')['default']
    ImgLoading: typeof import('./src/components/ImgLoading.vue')['default']
    NavigationBar: typeof import('./src/components/home/NavigationBar.vue')['default']
    PageButton: typeof import('./src/components/home/PageButton.vue')['default']
    PageFooter: typeof import('./src/components/home/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/home/PageHeader.vue')['default']
    PopUpBox: typeof import('./src/components/PopUpBox.vue')['default']
    QLoading: typeof import('./src/components/QLoading.vue')['default']
    RankCategory: typeof import('./src/components/rank/RankCategory.vue')['default']
    RechargeBox: typeof import('./src/components/user/RechargeBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserFollow: typeof import('./src/components/user/UserFollow.vue')['default']
  }
}
